services:
  backend:
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /app
          ignore:
            - node_modules/
    network_mode: service:nginx
    environment:
      - SERVICE=${SERVICE}
    depends_on:
      - redis

  frontend:
    build:
      context: frontend
      target: development
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
    network_mode: service:nginx

  redis:
    image: redis:7.4.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.local.conf:/usr/local/etc/redis/redis.conf:ro
    network_mode: service:nginx